spring:
  boot.admin.client:
    enabled: false
    url: http://localhost:8089
    instance:
      service-base-url: http://localhost:8080/
      prefer-ip: false
  application.name: zeebe-kafka-connect
  jmx.enabled: true
  cloud:
    function.definition: deplopmentNotification
    stream:
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
                      configuration.security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      bindings:
        applicationMetrics.destination: process-metrics
        
        deplopmentNotification-in-0:
          binder: kafka1
          destination: deployment-notification
          group: deplopmentNotification
      kafka:
        bindings:
          deplopmentNotification-in-0:
            consumer:
              startOffset: earliest
              resetOffsets: true
        binder:
          consumerProperties:
            topic.prefix: (.*)[-_][0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
            topic.prefixIsPattern: true
            topic.suffix: -responses
            isolation.level: read_committed
            max.poll.records: 5
            max.poll.interval.ms: 120000
          producerProperties:
            topic.suffix: -requests
          transaction:
            transaction-id-prefix: kafka-connect-${random.uuid}-
            producer:
              configuration:
                max.in.flight.requests.per.connection: 1
                retries: 1
                acks: all
                enable.idempotence: true
logging:
  file:
    name: ./logs/${spring.application.name}.log
    max-file-size: 5MB
    clean-history-on-start: false
  pattern:
    rolling-file-name: ./logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
  level:
    org.apache.kafka.clients: info
    io.camunda.zeebe.client: info
management:
  metrics:
    export:
      elastic:
        enabled: false
        step: 5s
        host: http://192.168.56.4:9200
        index: metrics-${spring.application.name}
        indexDateFormat: yyyy-MM-dd
  endpoints:
    health.binders.enabled: true
    enabled-by-default: true
    web:
      exposure.include: '*'
      cors:
        allowed-origins: '*'
        allowed-methods: GET,POST,PUT
    jmx.exposure.include: '*'
  endpoint:
    health.show-details: always
zeebe.client:
  requestTimeout: 10000
  broker.gatewayAddress: ${ZEEBE_BROKER_GATEWAY:localhost:26500}
  security.plaintext: ${ZEEBE_BROKER_SECURITY_PLAINTEXT_ENABLED:true}
  worker:
    maxJobsActive: 1
    threads: 1
  poller:
    correlationKey: eventId
    jobType: ticketProcessing
  job:
    timeout: 5m
wrapper:
  responseWrapperKey: response
job-storage:
  jobRemovalEnabled: false
  exceptionIgnoreEnabled: false