sleep.time.second: 1
spring:
   boot.admin.client:
      enabled: true
      url: http://localhost:8089
      instance:
         service-base-url: http://localhost:${server.port}/
         prefer-ip: false
   application.name: zeebe-kafka-connect
   jmx.enabled: true
   cloud:
      function.definition: validatingRequests;waitingForApprovalTickets;approvedTickets
      stream:
         binders:
            kafka1:
               type: kafka
               environment:
                  spring:
                     cloud:
                        stream:
                           kafka:
                              binder:
                                 brokers: ${bootstrap.server}
         bindings:
            applicationMetrics.destination: ${tenant.prefix}.process-metrics
            validatingRequests-out-0:
               binder: kafka1
               destination: ${tenant.prefix}.ticket-validation-requests
            validatingRequests-in-0:
               binder: kafka1
               destination: ${tenant.prefix}.ticket-validation-responses
               group: validation
         kafka:
            bindings:
               validatingRequests-out-0:
                  producer:
                     topic.properties:
                        retention.ms: 600000
               validatingRequests-in-0:         
                  consumer:
                     configuration:
                        isolation.level: read_committed
                        max.poll.records: 5
                        max.poll.interval.ms: 300000
               ticket-validation-in-0:
                  consumer:
                     configuration:
                        isolation.level: read_committed
                        max.poll.records: 5
                        max.poll.interval.ms: 300000
            binder:
               consumerProperties:
                  topic.suffix: -responses
               producerProperties:
                  topic.suffix: -requests
               transaction:
                  transaction-id-prefix: approval-
                  producer:
                     configuration:
                        max.in.flight.requests.per.connection: 1
                        retries: 1
                        acks: all
                        enable.idempotence: true
logging:
   file:
      name: ./logs/${spring.application.name}.log
      max-file-size: 10MB
      max-history: 2
      total-size-cap: 30MB
      clean-history-on-start: true
   pattern:
      rolling-file-name: ./logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
   level:
      org.apache.kafka.clients: info
      io.camunda.zeebe.client: trace
management:
   metrics:
      export:
         atlas:
            enabled: false
            step: 5s
            uri: http://localhost:7101/api/v1/publish
         elastic:
            enabled: false
            step: 5s
            host: http://192.168.56.4:9200
            index: metrics-${spring.application.name}
            indexDateFormat: yyyy-MM-dd
   endpoints:
      health.binders.enabled: true
      enabled-by-default: true
      web:
         exposure.include: '*'
         cors:
            allowed-origins: '*'
            allowed-methods: GET,POST,PUT
      jmx.exposure.include: '*'
   endpoint:
      health.show-details: always
camunda.bpm.client:
   base-url: http://192.168.56.4:8099/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
   lock-duration: 300000 # defines how many milliseconds the External Tasks are locked until they can be fetched again
   subscriptions:
      validatingTickets:
         variable-names: type,amount,totalCostAmount
         process-definition-key: TicketApprovalProcess
      approvedTickets:
         variable-names: type,amount,totalCostAmount,isValid,isApproved
         process-definition-key: TicketApprovalProcess
zeebe.client:
   broker.gatewayAddress: 10.10.15.219:8080
   security.plaintext: true
   worker:
      maxJobsActive: 1
      threads: 1
   poller:
      correlationKey: ticketId   
      jobType: ticketProcessing